{{- if .Values.db.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.name }}
  labels:
    {{- include "voting-app.db.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: "db-service"
    port: 5432
    targetPort: 5432
  selector:
    {{- include "voting-app.db.labels" . | nindent 4 }}
{{- end }}
