{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: database-postgres-policy
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.db.name }}
  ingress:
  # Allow from worker and result frontend
  - from:
    - podSelector:
        matchLabels:
          app: {{ .Values.worker.name }}
    - podSelector:
        matchLabels:
          app: {{ .Values.result.name }}
    ports:
    - protocol: TCP
      port: 5432
  # Allow from backup CronJob pods
  - from:
    - podSelector:
        matchLabels:
          app: {{ .Values.db.name }}
          app.kubernetes.io/component: backup
    ports:
    - protocol: TCP
      port: 5432
  egress: []

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: database-redis-policy
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.redis.name }}
  ingress:
  # Allow from vote frontend and worker
  - from:
    - podSelector:
        matchLabels:
          app: {{ .Values.vote.name }}
    - podSelector:
        matchLabels:
          app: {{ .Values.worker.name }}
    ports:
    - protocol: TCP
      port: 6379
  egress: []
{{- end }}
