{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: db-policy
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: database
      app.kubernetes.io/part-of: {{ include "voting-app.name" . }}
      app: db
  ingress:
  # Allow ingress only from backend and result frontend
  - from:
    - podSelector:
        matchLabels:
          app: worker
    - podSelector:
        matchLabels:
          app: result
    ports:
    - protocol: TCP
      port: 5432
  # Allow ingress from backup job
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/component: backup
    ports:
    - protocol: TCP
      port: 5432
  egress: []  # No egress needed for database

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: redis-policy
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: database
      app.kubernetes.io/part-of: {{ include "voting-app.name" . }}
      app: redis
  ingress:
  # Allow ingress only from frontend and backend
  - from:
    - podSelector:
        matchLabels:
          app: vote
    - podSelector:
        matchLabels:
          app: worker
    ports:
    - protocol: TCP
      port: 6379
  egress: []  # No egress needed for database
{{- end }}
