{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.name }}
  labels:
    {{- include "voting-app.redis.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: "redis-service"
    port: 6379
    targetPort: 6379
  selector:
    {{- include "voting-app.redis.labels" . | nindent 4 }}
{{- end }}
